# Generated by Django 4.1.4 on 2022-12-13 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSchemaCol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="column name",
                    ),
                ),
                (
                    "data_type",
                    models.IntegerField(
                        choices=[
                            (
                                0,
                                "Full name (a combination of first name and last name)",
                            ),
                            (1, "Job"),
                            (2, "Email"),
                            (3, "Domain name"),
                            (4, "Phone number"),
                            (5, "Company name"),
                            (
                                6,
                                "Text (with specified range for a number of sentences)",
                            ),
                            (7, "Integer (with specified range)"),
                            (8, "Address"),
                            (9, "Date"),
                        ],
                        verbose_name="type",
                    ),
                ),
                ("order", models.PositiveIntegerField(blank=True, default=0)),
                (
                    "data_range_from",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="from"
                    ),
                ),
                (
                    "data_range_to",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="to"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="schema",
            name="file",
        ),
        migrations.RemoveField(
            model_name="schema",
            name="name",
        ),
        migrations.AddField(
            model_name="schema",
            name="column_separator",
            field=models.CharField(
                choices=[
                    (",", "Comma (,)"),
                    (";", "Semicolon (;)"),
                    ("\t", "Tab (\t)"),
                    (" ", "Space ( )"),
                    ("|", "Vertical bar (|)"),
                ],
                default=",",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="schema",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schema",
            name="string_character",
            field=models.CharField(
                choices=[('"', 'Double-quote (")'), ("'", "Single-quote (')")],
                default='"',
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="schema",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="schema",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_schemas",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="schema",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name="DataSchemaRow",
        ),
        migrations.AddField(
            model_name="dataschemacol",
            name="target_schema",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schema_columns",
                to="app.schema",
            ),
        ),
    ]
