# Generated by Django 4.1.4 on 2022-12-13 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_dataschemacol_remove_schema_file_remove_schema_name_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DataSchemaCol",
            new_name="SchemaColumn",
        ),
    ]
